### ISSUE TITLE
Editor Bug can´t deselect the object you clicked

### ISSUE THREAD

**Issue by GodPowerYT** [OrfeasZ/ZHMModSDK#109]
For me it is when i deselect it doesn´t work and just stays there.

**Comment by GodPowerYT** [comment]
it is like when i click on the object and i click the deselect button the blue outlines will just stay there
Forever

**Comment by GodPowerYT** [comment]
Uploading Unbenanntes Video – Mit Clipchamp erstellt (1).mp4…

**Comment by GodPowerYT** [comment]
![Screenshot 2024-05-19 193400](https://github.com/OrfeasZ/ZHMModSDK/assets/170188647/5b9ac36d-1357-4320-a055-05abc27dd078)

**Comment by GodPowerYT** [comment]
https://github.com/OrfeasZ/ZHMModSDK/assets/170188647/11a7652c-9af5-4ea0-8173-e6d6c501d2b7

**Comment by GodPowerYT** [comment]
Yes

**Comment by OrfeasZ** [comment]
Then that's why. Disable the Debug mod.
