### ISSUE TITLE
Options flash on screen whenever playing game

### ISSUE THREAD

**Issue by Skylash777** [OrfeasZ/ZHMModSDK#124]
![2024-09-01](https://github.com/user-attachments/assets/6a8c299b-475f-460a-954e-402a8f9a6d21)
This appears whenever I start the game. I am using peacock, so that might be the problem? I also have SMF installed

In game: 

![Screenshot (4)](https://github.com/user-attachments/assets/7558c670-0933-4c5b-8820-792e339c028f)

![Screenshot (5)](https://github.com/user-attachments/assets/c8ac79d9-4331-4b93-b04f-3eb9dbcc4e16)

Edit: It Isnt peacock, loaded without

![Screenshot (6)](https://github.com/user-attachments/assets/91794b0f-885c-4eb6-a1e4-8c27dfd81d95)

**Comment by Skylash777** [comment]
:(

**Comment by OrfeasZ** [comment]
This is because you have the Editor mod enabled. You can disable it by pressing the `~` key, pressing `Mods` and unticking `Editor`.
