### ISSUE TITLE
FreeCam pause issue

### ISSUE THREAD

**Issue by DominicKiaune** [OrfeasZ/ZHMModSDK#143]
I'm not sure if its by design now but since the PR for FreeCam pause been merged, if in freecam game is unpaused, 47 keeps walking while the camera is moving and can interact with anything. I doubt this is a desired effect given there is F3 for that? And it seems the teleport kinda stopped working?

**Comment by OrfeasZ** [comment]
See #138. This hasn't been fully updated to support the latest version yet.
