### ISSUE TITLE
Just turning on FreeCam crashes the game

### ISSUE THREAD

**Issue by MECHASO** [OrfeasZ/ZHMModSDK#15]

**Comment by Notexe** [comment]
The SDK hasn't been updated to support the latest game update yet.

**Comment by vnikopol** [comment]
> he SDK hasn't been updated to support the latest game update yet.

do you have any plan to fix to support the current version?

**Comment by OrfeasZ** [comment]
Fixed in [v1.5.0](https://github.com/OrfeasZ/ZHMModSDK/releases/tag/v1.5.0).
