### ISSUE TITLE
Broken controls after restarting without exiting FreeCam

### ISSUE THREAD

**Issue by Deji69** [OrfeasZ/ZHMModSDK#18]
Using a controller. When entering FreeCam, the game is still running, so I will sometimes pause the game, resulting in the usual pause menu but still allowing me to adjust the camera. If I then restart the level, some of the game controls are broken until I enter free cam and exit again.

Ideally FreeCam should automatically restore the controls when the level is restarted.

**Comment by OrfeasZ** [comment]
Fixed in v1.6.0.
