### ISSUE TITLE
No dialog appear when game is opened

### ISSUE THREAD

**Issue by E-Lian** [OrfeasZ/ZHMModSDK#20]
>When the game opens, you'll see a dialog asking you which mods you'd like to use. Select them and press OK. You might need to restart your game for some of them to work.

I followed all the instructions but there was no dialog when I opened the game.

**Comment by E-Lian** [comment]
I am playing on Steam using Windows 10. The game version is 3.100.0. The game hasn't been updated since I first played it on February 26.

**Comment by OrfeasZ** [comment]
The Steam version isn't currently supported, and since I don't have access to it I can't do much to support it right now. You can track #16 for progress on that front when that changes.
