### ISSUE TITLE
Patch 3.110.0

### ISSUE THREAD

**Issue by Deji69** [OrfeasZ/ZHMModSDK#21]
Latest Hitman 3 patch seems to have broken the loader. Add support for the latest game version.

**Comment by MECHASO** [comment]
Yeah, Freecam doesn't crash the game, just does nothing

**Comment by peerlessjim** [comment]
hey, i just follow the usage you wrote and nothing happened. no dialog, nothing. Is the Freecam mod available for this game?

**Comment by msr8** [comment]
I am playing on 3.110.0 and after installing, when I run the game launcher and hit play, the game doesnt start

**Comment by AyoFixtheSDK** [comment]
Latest game update, same issue

**Comment by OrfeasZ** [comment]
Fixed in v1.6.0.
