### ISSUE TITLE
Please Update the SDK for Hitman III

### ISSUE THREAD

**Issue by AyoFixtheSDK** [OrfeasZ/ZHMModSDK#23]
The mod hasn't worked since patch 3.110.0
I've installed it properly, and it used work before that patch, but now the only thing pressing the tilde key does is bring up the cursor, which implies that certain aspects of the SDK still work, but the menu to turn any options on, or using any hotkeys does absolutely nothing. I've labelled this as a new issue hopefully to get your attention, I don't know if you plan on maintaining this mod anymore, but please if this could be updated when Hitman III gets its "freelancer mode" update, as that'll bring a lot of players, myself included, back to the game, and I want to record some cinematics that are only possible with your SDK camera mod.

**Comment by OrfeasZ** [comment]
Fixed in v1.6.0.
