### ISSUE TITLE
Game Freeze when starting on steam with last version

### ISSUE THREAD

**Issue by ThomasRbn** [OrfeasZ/ZHMModSDK#38]
Hello there, i tried to install the last version of the SDK, but when I launch the game, it freezes, then I'm forced to quit the game with an ALTF4. I also installed the debug version the check if there is a problem while loading the game. But it show no errors :/

![console](https://user-images.githubusercontent.com/100950259/215319511-f36855e6-6806-4a66-9dac-ac9c70e4ecd1.png)
![freeze](https://user-images.githubusercontent.com/100950259/215319515-a0966c3b-4df4-4ca7-8d56-e3fc969c0401.png)

**Comment by ThomasRbn** [comment]
Wrong click mb

**Comment by ThomasRbn** [comment]
Well, idk how, but the game has launched, but discord rich presence mod cannot be load (with error code 126)
![console](https://user-images.githubusercontent.com/100950259/215320579-f3bb1871-86e2-4160-97de-9844c68a1af8.png)

**Comment by Notexe** [comment]
Discord rich presence requires additional setting up which is probably why it's failing to load.

**Comment by ThomasRbn** [comment]
I followed the mod additional setup (adding the lib folder to Retail)

**Comment by Notexe** [comment]
You don't add the entire lib folder, you need to add discord_game_sdk.dll to the retail folder

**Comment by ThomasRbn** [comment]
Ohhh ok my bad -_- I moved all the content,and it works, thank you ^^
