### ISSUE TITLE
Game doesn't get past launcher on Epic

### ISSUE THREAD

**Issue by HW12Dev** [OrfeasZ/ZHMModSDK#40]
After installing 1.7.0, the game opens the launcher like normal, and then crashes when the game tries to open.
I have no overlays enabled, no controllers plugged in and I've tried compatibility settings.

**Comment by OrfeasZ** [comment]
@HW12Dev can you try this: https://github.com/OrfeasZ/ZHMModSDK/issues/37#issuecomment-1408956191

**Comment by HW12Dev** [comment]
it works now

**Comment by HW12Dev** [comment]
but it is quite inconvenient being unable to configure debugmod

**Comment by OrfeasZ** [comment]
That's ok, I just wanted to see if the root cause was the same. I'll keep the other issue open for tracking this until I fix it.
