### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by geicorules** [OrfeasZ/ZHMModSDK#5]
Sorry if this is the wrong place I didn't see a forum to ask these questions. 
I understand this is new so there isn't much explanation on some of the mods

1. CertPinBypass : Does this mod do anything at the moment? Is the intention that we could make a fake spoofed IoI server so we could play offline but let the game think we are online and level up etc? 

2.  As for the mod loader does it currently only support the mods listed here? Do the mods require dll. Will this allow for downloading of mods off of nexus and placing them here in a folder and the mod loader does the job of putting them in the proper place?

Sorry I am not a modder but am very interested in where this project is going. 
It would be ideal if we could play this game offline and still unlock items and be able to see our SA icon and even getting a rating even if it wasn't published to the leaderboards. Besides the leaderboards are already plagued with cheaters so they aren't of actual use. 

Once again sorry in advance if this isn't where this should go and keep up the good work its thanks to people like you that games like this can live on past when the devs decide to support it.

**Comment by OrfeasZ** [comment]
1. The mod does something similar to the localghost patcher, which is to disable certificate pinning. This means that when this mod is enabled, the game can connect to any third party server with trusted certificates, not just the IOI one. You could of course use that with an emulated server locally but that's beyond the scope of this specific mod.
2. This loader supports only mods made for it using the SDK, which right now are the ones listed in the README (afaik nobody else has made any mods using it yet). Every mod is a DLL that needs to be placed in the mods folder to be used. Mods on Nexus Mods are generally file mods (ie. they modify the game's files), while mods made using this SDK are runtime mods, which means they can for the most part survive game updates and change things at runtime, without modifying any game files.

**Comment by geicorules** [comment]
Cool this clears up a lot I appreciate it.
