### ISSUE TITLE
How to install mods from nexusmods

### ISSUE THREAD

**Issue by maplepy** [OrfeasZ/ZHMModSDK#50]
How would I install mods from here: https://www.nexusmods.com/hitman3/mods/ ?

**Comment by OrfeasZ** [comment]
Most mods on there will have instructions you can follow, and most of them will probably require using [Simple Mod Framework](https://www.nexusmods.com/hitman3/mods/200).

**Comment by maplepy** [comment]
Thing is, I'm on linux so thats why I was wondering if there was a simple way to install them like you made it for this project

**Comment by maplepy** [comment]
So is there any way for me to put the mods into the same format as you do?

**Comment by OrfeasZ** [comment]
I'm afraid I don't know.
