### ISSUE TITLE
[Debug Mod] Many assets crash the game

### ISSUE THREAD

**Issue by bennett-sh** [OrfeasZ/ZHMModSDK#55]
Adding/giving specific props using the asset menu crashes the game. This mostly happens with but isn't exclusive to S3 items.

**Comment by musicalmushr00m** [comment]
Can confirm that lots of "S3" props cause crashing in the asset selector. Same behavior if spawned in world or in inventory. Wonder if it's a REPO issue and how fixable it is.

**Comment by OrfeasZ** [comment]
This should be fixed in the latest version.
