### ISSUE TITLE
Advanced Rating mod is not mentioned in the Documentation + Game Crashing bug when is used

### ISSUE THREAD

**Issue by FlamingLily** [OrfeasZ/ZHMModSDK#57]
As the title says. I would post this on the github page for the Advanced Ratings mod, but it's not linked.

When playing with Advanced Ratings enabled, placing, throwing, dropping, or retrieving the Bubble Queen sedative gum (from 7 Deadly Sins; Gluttony) from a briefcase instantly crashes the game.

**Comment by Deji69** [comment]
I believe this is related to #56 due to the quotes in `"Bubble Queen" Gum Pack`.

**Comment by FlamingLily** [comment]
Yeah, looks like you're right. Went into holiday hoarders with AdvancedRating disabled, killed "Smokey", and the game was fine. Turned it on and killed "Slick" and the game instantly crashed in exactly the same way. Seeing as it's likely the same issue, I'm going to close this and throw a comment on #56 to the effect of this issue.
