### ISSUE TITLE
Npcs in containers

### ISSUE THREAD

**Issue by geicorules** [OrfeasZ/ZHMModSDK#6]
Passified npcs put into containers will pop out after their time to wake up and will stand infront of the container and not move but can still react to suspicious actions.

**Comment by OrfeasZ** [comment]
They might've changed the flags in one of the recent updates. Will take a look once I have some time.

**Comment by OrfeasZ** [comment]
This is fixed in [v1.4.0](https://github.com/OrfeasZ/ZHMModSDK/releases/tag/v1.4.0).
