### ISSUE TITLE
UI Overlay messed up

### ISSUE THREAD

**Issue by LedLoaf** [OrfeasZ/ZHMModSDK#63]
Hello,

I'm new to modding Hitman 3, and unfortunately it feels really jankey, but I got ZHM, this ReShader program, and simple framework. 

As I understand it, 'home' opens the ReShader program and '~' opens the overlay on ZHM. Unfortunately, when I press it, nothing happens except my cursor changes. I have to press it again to be able to navigate Hitman3. If I spam it enough times, I get a little glimpse of what it looks like (or hold '~' down). It looks red, and I see some mod options and an OK button. Unfortunately, I can't get it to stay up like the ReShader overlay easily does.

Any help?

Newest release version
Windows 11
Geforce 4090

PS: I tried to search for this answer, and it looked like someone had this before, but I didn't get a solution.

EDIT: Actually, during the loading screen, it was working fine. After that, I can't access it at StartUp, Intro, MainMenu, Game. Just loading screen which is pretty fast.

**Comment by OrfeasZ** [comment]
See last comment in #77 for a possible solution.
