### ISSUE TITLE
Change console key

### ISSUE THREAD

**Issue by chairinpool** [OrfeasZ/ZHMModSDK#64]
Is there a way I can change the hotkey to open the overlay?

**Comment by OrfeasZ** [comment]
This is now possible in the latest version.

To change the console key, open the `mods.ini` file and add the following:

```ini
[sdk]
console_key = 0x29
```

(If the `[sdk]` section already exists, just add the `console_key` key / value)

You can replace `0x29` (tilde / grave key) with a scan code of your choice. See [this table](https://learn.microsoft.com/en-us/windows/win32/inputdev/about-keyboard-input#scan-codes) for a list of scan codes by key (column named `Scan 1 Make`).

For example, to change it to `F1`, write the following:
```ini
[sdk]
console_key = 0x3B
```

**Comment by BigFish619000** [comment]
Hi Their, I was wondering if I could change Freecam`s Teleport function to another key, instead of Ctrl + F9. would it be possible to change this somewhere in the Z files, so I only have to use a single key or any other of my choice?
