### ISSUE TITLE
Editor: unknown parameter type crash

### ISSUE THREAD

**Issue by vitphire** [OrfeasZ/ZHMModSDK#73]
The game crashes when displaying[^1] an entity that has a parameter with a strange type (such as ZVariant).
This is easily replicated by going into any mission, and searching for `c939a97390c99d0e` as ID.
The editor window displays it correctly (**M_Value** ZVariant (Unsupported)), but the game crashes on the next frame.

[^1]: The crash happens while creating the JSON, not while displaying

**Comment by OrfeasZ** [comment]
Should be fixed in fad420b. You can find a pre-release build with this fix [here](https://github.com/OrfeasZ/ZHMModSDK/actions/runs/6830153061).
