### ISSUE TITLE
[FreeCam] "Keeps camera still while you control 47" doesn't work

### ISSUE THREAD

**Issue by nick21500** [OrfeasZ/ZHMModSDK#8]
About what it says on the tin; there's no way to move 47 while the free camera is enabled. The readme says Left Bumper is assigned to this but it doesn't do anything as far as I can tell. I tried to dig through some files but I'm out of my depth haha.
If it's relatively easy to modify, it'd also be awesome to have a KBM binding or the ability to toggle/hold.

This tool is awesome though, I've been looking for a nice H3 freecam. Thanks!

**Comment by nick21500** [comment]
@OrfeasZ

**Comment by dribbleondo** [comment]
Can confirm, this feature does not work @OrfeasZ

**Comment by OrfeasZ** [comment]
Fixed in [v1.5.0](https://github.com/OrfeasZ/ZHMModSDK/releases/tag/v1.5.0).

**Comment by nick21500** [comment]
legend <3
