### ISSUE TITLE
Regarding a Reupload on Nexus Mods

### ISSUE THREAD

**Issue by PasttaTypo** [OrfeasZ/ZHMModSDK#80]
Hey, there's a reupload of the ZHM Mod SDK up on [Nexus Mods.](https://www.nexusmods.com/hitman3/mods/628?tab=description) I don't think that creator got permission to reupload, but I wanted to let you know so you can either request a takedown or whatevs.
Pretty sure the re-uploader didn't do it with malice, but I can't vouch that the files are 100% safe.

**Comment by OrfeasZ** [comment]
Thanks, I'm already aware and have reported it.
