### ISSUE TITLE
[DebugMod] Assets not loading the list

### ISSUE THREAD

**Issue by jagltoro** [OrfeasZ/ZHMModSDK#83]
The title. Activating DebugMod and going to Assets tab, nothing is displayed on the list of Props

![Screenshot 2023-12-04 224120](https://github.com/OrfeasZ/ZHMModSDK/assets/6497296/11011b05-768f-411c-938e-89453a47e827)

**Comment by OrfeasZ** [comment]
Fixed in [v2.0.0-rc.2](https://github.com/OrfeasZ/ZHMModSDK/releases/tag/v2.0.0-rc.2).
