### ISSUE TITLE
Hitman 3 RTX 4060 TI ZHMModSDK keeps flashing or not showing the menu, 

### ISSUE THREAD

**Issue by AxelAlinsky** [OrfeasZ/ZHMModSDK#86]
I am having trouble with the mode while playing Hitman 3. A short background: I can choose between Nvidia GeForce RTX 4060 TI and Intel(R) UHD Graphics 770 when launching the game. However, the mod works fine on Intel, but when I use The RTX, the mod menu keeps flashing during the game, and sometimes it doesn't show the menu at all. I do think this is the GPU problem because I tested it on my laptop, which has the RTX 2040, and it had no issue. 

Below is a video where I start the benchmark (more straightforward to show for debugging). After loading, the menu just automatically disappears, but when I toggle it on/off, the mouse appears.

Troubleshooting Info: 
Platform: Steam
OS: Windows 11
GPU: RTX 4060 TI
CPU: Intel I7 13

https://github.com/OrfeasZ/ZHMModSDK/assets/66462743/53cb4ffa-32b7-4713-a793-38468938dd65

**Comment by OrfeasZ** [comment]
Can you try with the latest build from [here](https://github.com/OrfeasZ/ZHMModSDK/actions/runs/7370673325/artifacts/1141043808) and let me know if you still have this issue?

**Comment by AxelAlinsky** [comment]
This works!! Thank so much!
