### ISSUE TITLE
Clumsy crashes the game

### ISSUE THREAD

**Issue by Xeokss** [OrfeasZ/ZHMModSDK#88]
Whenever i enable Clumsy mod, the game just lags a bunch and then crashes

**Comment by Umaroth** [comment]
Same, I have it installed properly via SMF but upon enabling it via the Debug menu and trying to lead a level the game crashes. Disable Clumsy via the debug menu and the levels load normally.

**Comment by OrfeasZ** [comment]
This should be fixed in 2.0.0.
