### ISSUE TITLE
Cant spawn assets!

### ISSUE THREAD

**Issue by FINDERSSS** [OrfeasZ/ZHMModSDK#89]
When trying to spawn assets i just cant none show up and if i type the name in anyways and try nothing happens please fix! thank you

**Comment by OrfeasZ** [comment]
Can you try with the latest build from here? https://github.com/OrfeasZ/ZHMModSDK/actions/runs/7370673325

**Comment by Richard-Creasman** [comment]
After trying to replicate on the newest release candidate linked, the assets menu works as intended after entering anything into the blank. Thanks for the fix!

**Comment by OrfeasZ** [comment]
Fixed in [v2.0.0-rc.2](https://github.com/OrfeasZ/ZHMModSDK/releases/tag/v2.0.0-rc.2).
