### ISSUE TITLE
Frame generation bug 

### ISSUE THREAD

**Issue by Xlotical** [OrfeasZ/ZHMModSDK#90]
Frame generation causes the menu to only appear when clicking on a entity

**Comment by OrfeasZ** [comment]
Can you try with the latest build from here? https://github.com/OrfeasZ/ZHMModSDK/actions/runs/7370673325

**Comment by OrfeasZ** [comment]
Fixed in [v2.0.0-rc.2](https://github.com/OrfeasZ/ZHMModSDK/releases/tag/v2.0.0-rc.2).
