### ISSUE TITLE
Game does not open after MOD installation

### ISSUE THREAD

**Issue by C0d31nj3ct10n** [OrfeasZ/ZHMModSDK#91]
Unfortunately, The game doesn't open after pasting mod files into `\path\to\Hitman3\Retail`. From the logs in ZHMModLoader.log, it looks like that you need to update the mod. Is there any solution or we have to wait for the newer version?

 > [!IMPORTANT]
 > The game is Hitman III Deluxe Edition (CODEX) & the mod version I was trying to install is 1.8.0
 
 Here is the log file that appeared in the root folder:
*[ZHMModLoader.log](https://github.com/OrfeasZ/ZHMModSDK/files/13989598/ZHMModLoader.log) (8.0KB)*

It'd be great if you answer as soon as possible.

**Comment by OrfeasZ** [comment]
Cracked copies are not supported. Buy the game.

**Comment by C0d31nj3ct10n** [comment]
Sorry but we cannot buy the game at Iran that's why I'm troubling.
You mean, this problem cannot be solved?
